apiVersion: v1
clusters:
- cluster:
    server: http://localhost:8080
  name: kwok
contexts:
- context:
    cluster: kwok
    namespace: default
  name: kwok
current-context: kwok
kind: Config
preferences: {}
users: null
